export default function handler(req, res) {
  const services = [
    { id: 1, name: 'Yard Work', freelancer: 'John Doe', price: '$20/hour', rating: 4.5 },
    {
      id: 2,
      name: 'Indoor Painting',
      freelancer: 'Jane Smith',
      price: '$30/hour',
      rating: 4,
    },
    {
      id: 3,
      name: 'Furniture Assembly',
      freelancer: 'Michael Lee',
      price: '$25/hour',
      rating: 3.2,
    },
    { id: 4, name: 'Plumbing', freelancer: 'Alice Brown', price: '$40/hour', rating: 4.8 },
    {
      id: 5,
      name: 'Yard Work',
      freelancer: 'David White',
      price: '$35/hour',
      rating: 4.3,
    },
    { id: 6, name: 'House Cleaning', freelancer: 'Maria Garcia', price: '$20/hour', rating: 4.7 },
    {
      id: 7,
      name: 'Gardening',
      freelancer: 'Robert Martinez',
      price: '$25/hour',
      rating: 4.1,
    },
    { id: 8, name: 'Dog Walking', freelancer: 'Olivia Johnson', price: '$15/hour', rating: 4.9 },
    {
      id: 9,
      name: 'Furniture Assembly',
      freelancer: 'William Rodriguez',
      price: '$10/hour',
      rating: 3.9,
    },
    {
      id: 10,
      name: 'Photography',
      freelancer: 'Sophia Wilson',
      price: '$50/hour',
      rating: 4.6,
    },
    {
      id: 11,
      name: 'Plumbing',
      freelancer: 'Daniel Moore',
      price: '$55/hour',
      rating: 4.4,
    },
    {
      id: 12,
      name: 'House Cleaning',
      freelancer: 'Isabella',
      price: '$40/hour',
      rating: 4.2,
    },
    {
      id: 13,
      name: 'House Cleaning',
      freelancer: 'Ethan',
      price: '$30/hour',
      rating: 4.8,
    },
    {
      id: 14,
      name: 'Electrical',
      freelancer: 'Mia',
      price: '$60/hour',
      rating: 4.5,
    },
    {
      id: 15,
      name: 'Electrical',
      freelancer: 'Aiden',
      price: '$20/hour',
      rating: 4.7,
    },
    {
      id: 16,
      name: 'Yard Work',
      freelancer: 'Sofia',
      price: '$25/hour',
      rating: 4.3,
    },
    {
      id: 17,
      name: 'Gardening',
      freelancer: 'Elijah',
      price: '$35/hour',
      rating: 4.1,
    },
    {
      id: 18,
      name: 'Dog Walking',
      freelancer: 'Avery',
      price: '$15/hour',
      rating: 4.9,
    },
    {
      id: 19,
      name: 'Photography',
      freelancer: 'James',
      price: '$50/hour',
      rating: 4.6,
    },
    {
      id: 20,
      name: 'Plumbing',
      freelancer: 'Aria',
      price: '$55/hour',
      rating: 4.4,
    },
  ]
  res.status(200).json(services)
}
